on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build for Release
        run: |
          env GOOS=darwin GOARCH=amd64 $(GO) build -o bin/haiku_darwin_amd64
          env GOOS=darwin GOARCH=arm64 $(GO) build -o bin/haiku_darwin_arm64
          env GOOS=linux GOARCH=amd64 $(GO) build -o bin/haiku_linux_amd64
          env GOOS=linux GOARCH=arm64 $(GO) build -o bin/haiku_linux_arm64
          sha256sum bin/* >> bin/SHA256SUMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/haiku_darwin_amd64
            bin/haiku_darwin_arm64
            bin/haiku_linux_amd64
            bin/haiku_linux_arm64
            bin/SHA256SUMS
